## Multistage build: First stage fetches dependencies
# 明确指定 fetcher 阶段在当前运行的 X86 宿主机平台（BUILDPLATFORM）上跑，这样下载速度极快！
FROM --platform=$BUILDPLATFORM alpine:3.20 AS fetcher

# install and copy ca-certificates, mailcap, and tini-static; download JSON.sh
RUN apk update && \
    apk --no-cache add ca-certificates mailcap tini-static && \
    wget -O /JSON.sh https://raw.githubusercontent.com/dominictarr/JSON.sh/0d5e5c77365f63809bf6e77ef44a1f34b0e05840/JSON.sh

## Second stage: 动态适应目标架构（TARGETPLATFORM）
FROM busybox:1.37.0-musl

# Define non-root user UID and GID
ENV UID=1000
ENV GID=1000

# BusyBox 里默认 nobody 是 65534:65534，这里把 nobody 映射成 99:100（nobody:users）
RUN sed -i 's/^nobody:x:65534:65534:/nobody:x:1000:1000:/' /etc/passwd

# 【关键注意】：你 COPY 进去的 filebrowser 二进制文件，必须是你刚刚编译好的 ARMv7 版本！
COPY --chown=nobody:users filebrowser /bin/filebrowser
COPY --chown=nobody:users docker/common/ /
COPY --chown=nobody:users docker/alpine/ /
COPY --chown=nobody:users --from=fetcher /sbin/tini-static /bin/tini
COPY --from=fetcher /JSON.sh /JSON.sh
COPY --from=fetcher /etc/ca-certificates.conf /etc/ca-certificates.conf
COPY --from=fetcher /etc/ca-certificates /etc/ca-certificates
COPY --from=fetcher /etc/mime.types /etc/mime.types
COPY --from=fetcher /etc/ssl /etc/ssl

# Create data directories, set ownership, and ensure healthcheck script is executable
RUN mkdir -p /config /database /srv && \
    chown -R nobody:users /config /database /srv \
    && chmod +x /healthcheck.sh

# Define healthcheck script
HEALTHCHECK --start-period=2s --interval=5s --timeout=3s CMD /healthcheck.sh

# Set the user, volumes and exposed ports
USER $UID:$GID

VOLUME /srv /config /database

EXPOSE 80

ENTRYPOINT [ "tini", "--", "/init.sh" ]